### ISSUE TITLE
Limit number of connections from a single host

### ISSUE THREAD

**Issue by degeri** [decred/dcrpool#124]
We should limit the number of connections a single host can do to the server. If we allow a single host to make too many client connections they might take up too much resources and might lead to a DOS.

Further we can also look into the idea of increasing the number of client connects for a host based on the hash power they provide (make it a sliding scale) . This would act as a good way to prevent a DOS since actual work needs to be done to prove hashpower to the server.

**Comment by dnldd** [comment]
Will look into dynamically increasing client connection limits based on work contributions associated with the host. For now a configurable limit will be used.

**Comment by degeri** [comment]
Closed by #127 and #125
