### ISSUE TITLE
Support payment processing requests.

### ISSUE THREAD

**Issue by dnldd** [decred/dcrpool#138]
Pool accounts should be able to request for payment processing if mature payments due them are below the minimum payment processing amount. This would be mostly used by pool accounts to claim mature unprocessed payments due them before leaving a mining pool.

**Comment by dnldd** [comment]
functionality has been added for this now, needs to usable via the pool ui.

**Comment by jholdstock** [comment]
If you could write up a spec for this I could probably get it implemented this afternoon/tomorrow

**Comment by dnldd** [comment]
Payment processing requests should be accessible to the gui in #143 once it's in, it requires just the address as a parameter. Also only one payment processing request can be created for an account at a time.
