### ISSUE TITLE
UI Update

### ISSUE THREAD

**Issue by dnldd** [decred/dcrpool#146]
Initial screens for dcrpool's ui update: https://xd.adobe.com/view/a814493c-193a-4dfc-5735-0e6d459a6924-de25/. Need to first take another look at the gui component and make improvements where needed before this gets implemented.

**Comment by jholdstock** [comment]
Love the new designs. I will assign this to myself and start making the changes soon

**Comment by dnldd** [comment]
Sure, let's get the updates discussed to the gui component done first. I've asked @buck54321 to take a look at the gui component and make suggestions on things we can improve since he played a key role in polishing dcrdata's UI/UX to what it is now.
