### ISSUE TITLE
GUI caching optimisation

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrpool#167]
Data cached for the GUI includes:

- Total pool hash rate
- Confirmed blocks mined by pool
- Work quotas describing reward distribution for accounts

The whole cache is currently refreshed once every 15 seconds. This is acceptable for the hash rate as it changes often, and it is simply a variable held in memory, but the other data is pulled from the database and should not be polled so often. Instead, we should only update the cache whenever the underlying data is changed.

**Comment by dnldd** [comment]
This has been resolved fully by #183, #185, #187 and #195.
