### ISSUE TITLE
Review use of go-spew in production code

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrpool#169]
`davecgh/go-spew` is used in production code:

https://github.com/decred/dcrpool/blob/f818a93af7bb036c096966e6111a386e55fb49fa/pool/client.go#L695

I believe we should be avoiding the use of go-spew in production code as it has a [dependency on the `unsafe` package](https://github.com/davecgh/go-spew#unsafe-package-dependency).

A comment from jrick on the topic: https://github.com/davecgh/go-spew/issues/106

We also use it a few times in the CPU miner, but I guess this is acceptable as the CPU miner is only intended for testing.

fyi: @davecgh, @jrick

**Comment by dnldd** [comment]
I'm opting to remove the use of `spew` entirely, relegating it to using it only when debugging. I noticed most of the cases where `spew` was being used were related to debugging scenarios where more information was needed, this isn't needed in production code. In other cases `spew` was being used to output more information than necessary, particularly in tests.

**Comment by davecgh** [comment]
This is fine for `dcrpool`, but I can say that `spew` will not be removed from use in dcrd because it is used for trace logging which is _extremely_ useful when dealing with protocol level things.
