### ISSUE TITLE
Handling for transaction fee > pool fee

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrpool#210]
With the new payment code in #207, the pool is going to cover reward payment transaction fees using its own portion of the mining reward. The amount of mining reward claimed by the pool is configurable, any value above zero is allowed. This enables a scenario which is not currently covered - the pool fee is too small to cover the transaction fees. We need special handling for this case because with the current code, no reward payments will ever be sent

**Comment by dnldd** [comment]
The payment code in #207 is still being tinkered with, I initially thought it'd make the most sense to deduct the tx fees from the pool fees collected on the block. But after noticing this issue in your review and thinking about it some more I think the best way to handle it is to have the participating accounts pay transaction fees instead. It is implicit that the pool fee would cover the costs involved in publishing the payout transaction on the network, therefore having the participating accounts pay for it is reasonable regardless of the percentage set for the pool fee. Each participating account will pay a percentage of the transaction fees based on the ratio of the amount it is being paid relative to the total payouts going out to participating accounts.

**Comment by jholdstock** [comment]
Yep this seems reasonable to me. This would mean that we need to put some kind of upper limit on the pool fee percentage, at the moment anything under 100% is accepted. We could reduce it to maybe 90%, just to take a potential footgun away from the pool operator.

Would be happy to see the change in a new PR tbh, 207 is already quite big and very nearly complete afaict

**Comment by dnldd** [comment]
Noted, I think we need to discuss that further on what the limits (lower and upper) should be. Also I already worked in the changes into #207 :grimacing:, the tests for `payDividends` will be in a new PR though.
