### ISSUE TITLE
Review usage of multiple pool fee addresses

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrpool#218]
Config allows multiple addresses to be provided for collecting pool fees. I had assumed that fees would be split equally among all provided addresses, however it seems that each time a payment is processed, a single fee address is selected **at random**.

https://github.com/decred/dcrpool/blob/2b8ba4522724d2c3ef7eccf415fbc4a91184ff9a/pool/paymentmgr.go#L748-L749

I am assuming this is a temporary behaviour and something which needs to be fixed. If this is a deliberate feature then it needs to be clearly documented with proper justification.

**Comment by dnldd** [comment]
Will get this done soon.

**Comment by dnldd** [comment]
Resolved by #225
