### ISSUE TITLE
Pool not starting

### ISSUE THREAD

**Issue by goodthebest** [decred/dcrpool#442]
Decred folks, 

Both dcrd and dcrwallet are running, blockchain is synced however pool is not starting, error screenshot also provided, please advise?

pool.conf 
```
rpcuser=yxGPHk9MXHnA0GC294=
rpcpass=fXPKw4TMAXpz9Cm/Ja/uU=
dcrdrpchost=127.0.0.1:9109
dcrdrpccert=/root/.dcrd/rpc.cert
walletgrpchost=127.0.0.1:9110
walletrpccert=/root/.dcrwallet/rpc.cert
maxgentime=20s
solopool=false
activenet=mainnet
walletpass=xAbcd1234x
poolfeeaddrs=DscAHuxBqbm8ys9zFaJG5LsTYQ4najCieaY
paymentmethod=pplns
lastnperiod=5m
adminpass=somepassword
guidir=/home/gui
```

**Error screenshot**
![image](https://github.com/user-attachments/assets/6eb8cd4d-1ec2-4c7c-8a9f-ffa50696e86a)

**Comment by davecgh** [comment]
Port 9110 is the wallet's JSON-RPC port.  The wallet's gRPC port is 9111 by default.  It looks like that is your issue.

EDIT: Also note that you don't actually need to specify `dcrdrpchsot` nor `walletgrpchost` when they are the defaults.

**Comment by goodthebest** [comment]
Here's dcrwallet's log, do I need to generate some sort of cert for gRPC to run?

```
2024-11-05 19:53:13.337 [INF] WLLT: Opened wallet
**2024-11-05 19:53:13.362 [WRN] DCRW: gRPC server is configured with listeners, but no trusted client certificates exist (looked in /root/.dcrwallet/clients.pem)**
2024-11-05 19:53:13.362 [WRN] DCRW: Can't listen on [::1]:9110: listen tcp6 [::1]:9110: bind: cannot assign requested address
2024-11-05 19:53:13.363 [INF] RPCS: Listening on 127.0.0.1:9110

```

**Comment by davecgh** [comment]
https://github.com/decred/dcrpool/blob/master/README.md#wallet-client-authentication

**Comment by davecgh** [comment]
In short, run dcrpool the first time with `--gencertsonly` which will create a `wallet.cert` and `wallet.key` certificate pair in the pool's home directory.

Then, you just need to append the contents of `wallet.cert` to the wallet's `clients.pem` to authorize access for the new client certificate.

So, based on your config above, something like:

```
$ ./dcrpool --configfile=pool.conf --gencertsonly
$ cat /root/.dcrpool/wallet.cert >> /root/.dcrwallet/clients.pem
```

Then, restart dcrwallet to make sure it picks up the updated authorized client certs.

On another note, if you put your `pool.conf` in the default location `/root/.dcrpool/dcrpool.conf`, then you don't have to specify the config file at all and can just run `dcrpool` without having to specify the config file every time.

**Comment by goodthebest** [comment]
gRPC seems fixed now, thanks.

Regarding --miningaddr, I tried to use this flag with wallet address both on dcrwallet and dcrd and dcrpool too, nowhere it seems to fit?

When I start pool getting this error?

```
root@vmi2187643:~/go/bin# ./dcrpool --configfile=pool.conf
2024-11-05 20:27:16.740 [INF] MP: dcrpool version 2.0.0 (Go version go1.23.2 linux/amd64)
2024-11-05 20:27:16.740 [INF] MP: Home dir: /root/.dcrpool
2024-11-05 20:27:16.750 [INF] POOL: Maximum work submission generation time at pool difficulty is 20s.
2024-11-05 20:27:16.750 [INF] POOL: Payment method is PPLNS.
2024-11-05 20:27:16.774 [ERR] MP: unable to get work from consensus daemon: unable to fetch current work: -32603: no payment addresses specified via --miningaddr
2024-11-05 20:27:16.774 [INF] MP: Shutdown complete

```

**Comment by davecgh** [comment]
It goes on dcrd.  It needs to be configured with your pool's mining address in order to generate block templates that pay to your pool.

So, add it to your `/root/.dcrd/dcrd.conf` file and restart dcrd.


https://github.com/decred/dcrd/tree/master/docs#Mining

**Comment by goodthebest** [comment]
in default dcrd.conf, isn't it for CPU mining only or it's applicable on pool too?

```
; Add addresses to pay mined blocks to for CPU mining and the block templates
; generated for the getwork RPC as desired.  One address per line.
; miningaddr=youraddress
; miningaddr=youraddress2
; miningaddr=youraddress3

```

**Comment by davecgh** [comment]
It's for the pool too.  The pool calls [the getwork JSON-RPC provided by dcrd](https://github.com/decred/dcrd/blob/master/docs/json_rpc_api.mediawiki#getwork) in order to obtain work that is then distributed to the miners via the stratum protocol.

In order to generate the work, dcrd has to make block templates, which naturally need to include an address to pay.  Hence, dcrd needs to be configured with the pool's address to be able to do that.

**Comment by goodthebest** [comment]
running gui on browser I'm getting this error:
`Client sent an HTTP request to an HTTPS server.`

Do I need to setup nginx with ssl?

**Comment by davecgh** [comment]
It depends on how you want to configure it.

You can either expose the pool directly, since it has its own webserver (and can be configured with let's encrypt instead of the default self-signed cert if you want via the --uselehttps) or do it via reverse proxy like nginx.

If you're going the reverse proxy route, you can either configure the RP to communicate with the pool via TLS (which you'd probably want to if it lives on another system) or disable TLS on the pool so the RP communicates with it in the clear (probably fine if you run it on the same machine and have otherwise secured your network).

See `dcrpool --help` for options.

```
$ dcrpool --help | grep noguitls
      --noguitls          Disable TLS on GUI endpoint (eg. for reverse proxy with a dedicated webserver).

$ dcrpool --help | grep uselehttps
      --uselehttps        This enables HTTPS using a Letsencrypt certificate. By default the pool uses a self-signed certificate for HTTPS.
```

**Comment by goodthebest** [comment]
Where the domain name needs to be mentioned e.g, in pool.conf or?

```
root@vmi2187643:~/go/bin# ./dcrpool --configfile=pool.conf --uselehttps
loadConfig: a valid domain is required for HTTPS via letsencrypt

```

**Comment by davecgh** [comment]
It's in the `dcrpool --help` options.

```
$ dcrpool --help | grep domain
      --domain:           The domain of the mining pool, required for TLS.
``` 

So, yes, you can put it in your pool configuration file like all the other options.

**Comment by goodthebest** [comment]
since I used domain and uselehttps, Boltdb seems corrupted? How can I restore or repair it?

```
root@vmi2187643:~/go/bin# ./dcrpool --configfile=pool.conf
2024-11-05 21:58:00.249 [INF] MP: dcrpool version 2.0.0 (Go version go1.23.2 linux/amd64)
2024-11-05 21:58:00.249 [INF] MP: Home dir: /root/.dcrpool
2024-11-05 21:58:01.205 [ERR] MP: failed to initialize database: openBoltDB: unable to open db file: timeout
2024-11-05 21:58:01.206 [INF] MP: Shutdown complete

```

**Comment by davecgh** [comment]
Not 100% sure on that.  I've always used postgres.

That said, given the error, it looks like it's timing out because it can't get the file lock on the database.  Make sure you aren't still running another instance of the pool.

If that's not it, maybe @jholdstock can help out.

**Comment by goodthebest** [comment]
Nevermind, it was a lock on the file. By restarting the server the problem was resolved.

Can decred be mined on this pool by an ASIC of blake3?

**Comment by davecgh** [comment]
No, at least there aren't any ASICs that I know of for DCR blake3.  Just because an ASIC can do blake3 doesn't mean it can mine decred since the hashing algorithm is only one part of mining.
