### ISSUE TITLE
Decred ASIC mining?

### ISSUE THREAD

**Issue by goodthebest** [decred/dcrpool#443]
Does Decred still support ASIC mining for BLAKE3?

**Comment by artikozel** [comment]
It does, but there aren't any BLAKE3 Decred miners out there and so far Decred has only been GPU mineable since the switch from BLAKE256r14 to BLAKE3 in September 2023.

**Comment by goodthebest** [comment]
@artikozel  I did setup dcrpool from this repo, however I wasn't able to connect Iceriverminer Alph Al0. Is there any particular setup I need to be able to use ASICs BLAKE3 miner such as Iceriverminer Alph Al0? Please advise?

**Comment by artikozel** [comment]
@goodthebest Iceriverminer Alph Al0 is not a Decred miner [as per the information available](https://www.asicminervalue.com/miners/iceriver/alph-al0) (_specifically targeting ALPH (Alephium)_), so I suspect it simply won't work.

**Comment by goodthebest** [comment]
@artikozel you are right, Iceriverminer Alph Al0 is for Alephium. My understanding was, since it's for BLAKE3 algo, it should work with Decred as well, as both share the same algo, isn't it? Or Decred's BLAKE3 is of different variant?

**Comment by artikozel** [comment]
The algo itself is one piece of the puzzle; unless it's applied specifically to the how Decred approaches mining it will not work.
In the words of @davecgh, dcrd lead dev:
> The hashing algorithm being the same is only a part of it.  It also has to understand exactly which bytes to hash and which bytes can be modified to produce the hash.  Also, iirc ALPH uses double blake3, and thus that wouldn't match either.
...
The devices, as they are, definitely won't work.  Now, whether or not it's possible to make them work would depend on exactly how they're implemented at the hardware level, what the interface between firmware and the core chips that performs the hashing is, and the specific firmware implementation details.  For example if the hardware always gives back a double hash, it would be impossible. In any case, if it is technically possible to get them to work, it most definitely wouldn't just be a case of twiddling a few options.  It would require intimate knowledge of the aforementioned things and the ability rewrite the firmware at a bare minimum.
