### ISSUE TITLE
Automatic updates for the UI

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrpool#96]
Can be achieved using web sockets.

Split out from #93

**Comment by jholdstock** [comment]
@dnldd  please specify which fields you think should be automatically updated, and what kind of time period for refreshing the data?

**Comment by dnldd** [comment]
the merged PR takes care of automatic update for the stats section. he reward percentages of participating needs automatic updates too (if the pool is in pool mining mode). This also goes for the blocks mined mined by pool list.
